# backend/routers/website.py

from fastapi import APIRouter, Depends, HTTPException, status, Response, Query
from sqlalchemy.orm import Session  
from sqlalchemy import func

from database import get_db
from models import Website
from database import get_db
from auth import get_current_user

router = APIRouter(prefix="/websites", tags=["websites"])

@router.post("/register")
def register_website(data: dict, db: Session = Depends(get_db), user = Depends(get_current_user)):
    # The site ID (UUID) is now automatically generated by the Website model's default=uuid4
    
    website = Website(
        name=data.get("name"),
        domain=data.get("domain"),
        owner=user
    )
    db.add(website)
    db.commit()
    db.refresh(website) # This populates website.id with the new UUID value

    # 🚨 FIX 1: Use the actual database ID (UUID) for the snippet and return value
    # The UUID object needs to be converted to a string for the URL
    site_uuid_str = str(website.id) 
    
    snippet = f'<script src="http://ec2-44-231-42-67.us-west-2.compute.amazonaws.com:8000/snippet/{site_uuid_str}.js"></script>'
    
    return {"site_id": site_uuid_str, "snippet": snippet}


@router.get("/")
def list_websites(db: Session = Depends(get_db), user = Depends(get_current_user)):
    websites = db.query(Website).filter(Website.owner == user).all()
    # 🚨 FIX 2: Access the 'id' column, not the deleted 'site_id'
    return [{"site_id": str(w.id), "name": w.name or w.domain} for w in websites]

@router.delete("/", status_code=status.HTTP_204_NO_CONTENT)
def delete_website(
    # 🚨 FIX: Explicitly tell FastAPI this parameter comes from the URL query string
    identifier: str = Query(..., description="The domain or name of the website to delete"), 
    db: Session = Depends(get_db),
    # You should also add user authorization here!
    user = Depends(get_current_user) # <-- Added security check
):
    """
    Deletes a website and all associated events, labels, and ignored patterns.
    """
    
    # 1. Find the website by domain or name, and ensure it belongs to the current user
    website = db.query(Website).filter(
        (Website.owner == user) & # <-- Added security check to prevent deleting other user's sites
        (
            (func.lower(Website.domain) == func.lower(identifier)) |
            (func.lower(Website.name) == func.lower(identifier))
        )
    ).first()
    
    if not website:
        # Note: We return 404 regardless of if the site exists or if it belongs to the user
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Website with identifier '{identifier}' not found or you do not own it."
        )

    # 2. Delete the website object
    db.delete(website)
    db.commit()

    return Response(status_code=status.HTTP_204_NO_CONTENT)