from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
# This revision creates the 'website' table.
revision = 'a7afee95e6b5'

# IMPORTANT: This must point to the *actual* revision ID of the Users table 
# file (which we manually set to 1234abcd5678 in the cleanup plan).
down_revision = '1234abcd5678'

branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'website',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website')
    # ### end Alembic commands ###